### ISSUE TITLE
[BUG] - 1 . Incorrect current year while initial setup

### ISSUE THREAD

**Issue by tsomuk** [SKemenov/MinimalCountdown#2]
**Description**
During initial setup, the current  year is incorrectly determined

**To Reproduce**
1. Add screensaver as new 
2. Go to option menu

**Screenshots**
![telegram-cloud-photo-size-2-5418230419796644754-x](https://github.com/SKemenov/MinimalCountdown/assets/123371636/e27d403d-8167-4279-92be-042cb3818a8f)

**Desktop**
- Device: MacBook Pro 16, Apple M2 Pro, 2023
- macOS: Sonoma 14.3.1

**Comment by SKemenov** [comment]
Fixed with commit [b47a2e7](https://github.com/SKemenov/MinimalCountdown/commit/b47a2e7eb3f990ba6f56bc41001456a85b295225)
